**Bayes and Naive Bayes Implementation and Analysis**

In [4]:
# ---------------------------------
# Machine Learning Project work
# Taha Heidari
# 2021
# Bayes and Naive Bayes Implementation and Analysis
# Dataset: IRIS Dataset
# ---------------------------------
# Obejctives: 
# Task: Implement the classifier without using ready-made Python Libraries

**Import librararies**

In [57]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, KFold 
from sklearn.metrics import accuracy_score, confusion_matrix
from scipy.stats import multivariate_normal
from math import sqrt, pi, exp


**Import Dataset**

In [6]:
iris = load_iris()
x_data = iris.data 
y_data = iris.target

# **A**

**Split Dataset**

In [81]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.30)
print('Number of Samples:', x_data.shape[0])
print('Number of Train Samples:', x_train.shape[0])
print('Number of Test Samples:', x_test.shape[0])

Number of Samples: 150
Number of Train Samples: 105
Number of Test Samples: 45


**Bayes Classifier**

In [82]:
class Bayes_Classifier:
    mu = None
    cov = None
    n_classes = None
    def __init__(self):
        a = None
    def pred(self,x):
        prob_vect = np.zeros(self.n_classes)
        for i in range(self.n_classes):
            mnormal = multivariate_normal(mean=bayes_classifier.mu[i], cov=bayes_classifier.cov[i])
            prior = 1./self.n_classes
            prob_vect[i] = prior*mnormal.pdf(x)
            sumatory = 0.
            for j in range(self.n_classes):
                mnormal = multivariate_normal(mean=bayes_classifier.mu[j], cov=bayes_classifier.cov[j])
                sumatory += prior*mnormal.pdf(x)
            prob_vect[i] = prob_vect[i]/sumatory
        return prob_vect
    def fit(self, X,y):
        self.mu = []
        self.cov = []
        self.n_classes = np.max(y)+1
        for i in range(self.n_classes):
            Xc = X[y==i]
            mu_c = np.mean(Xc, axis=0)
            self.mu.append(mu_c)
            cov_c = np.zeros((X.shape[1], X.shape[1]))
            for j in range( Xc.shape[0]):
                a = Xc[j].reshape((X.shape[1],1))
                b = Xc[j].reshape((1,X.shape[1]))
                cov_ci = np.multiply(a, b)
                cov_c = cov_c+cov_ci
            cov_c = cov_c/float(X.shape[0])
            self.cov.append(cov_c)
        self.mu = np.asarray(self.mu)
        self.cov = np.asarray(self.cov)

**Fit & Predict**

In [83]:
# Lists
y_train_acc_list = []
conf_mat_train_list = []
y_test_acc_list = []
conf_mat_test_list = []


for count in range (4):    
  # Splite
  x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.30)

  # Fit
  bayes_classifier = Bayes_Classifier()
  bayes_classifier.fit(x_train,y_train)

  # Pridict
  y_train_pred = []
  for i in range(x_train.shape[0]):
    y_train_pred_prob = bayes_classifier.pred(x_train[i,:])
    if (y_train_pred_prob[0] > y_train_pred_prob[1]) & (y_train_pred_prob[0] > y_train_pred_prob[2]):
      y_train_pred.append(0)
    elif (y_train_pred_prob[1] > y_train_pred_prob[0]) & (y_train_pred_prob[1] > y_train_pred_prob[2]):
      y_train_pred.append(1)
    else :
      y_train_pred.append(2)
  y_train_pred = np.array(y_train_pred)
  y_test_pred = []
  for i in range(x_test.shape[0]):
    y_test_pred_prob = bayes_classifier.pred(x_test[i,:])
    if (y_test_pred_prob[0] > y_test_pred_prob[1]) & (y_test_pred_prob[0] > y_test_pred_prob[2]):
      y_test_pred.append(0)
    elif (y_test_pred_prob[1] > y_test_pred_prob[0]) & (y_test_pred_prob[1] > y_test_pred_prob[2]):
      y_test_pred.append(1)
    else :
      y_test_pred.append(2)
  y_test_acc_list.append(y_test_acc)

  # Train: Accuracy & Confusion Matrix
  y_train_acc = accuracy_score(y_train, y_train_pred)
  y_train_acc_list.append(y_train_acc)
  conf_mat_train = confusion_matrix(y_train, y_train_pred)
  conf_mat_train_list.append(conf_mat_train)

  # Test: Accuracy & Confusion Matrix
  y_test_pred = np.array(y_test_pred)
  y_test_acc = accuracy_score(y_test, y_test_pred)
  conf_mat_test = confusion_matrix(y_test, y_test_pred)
  conf_mat_test_list.append(conf_mat_test)

**Result: Accuracy**

In [84]:
for i in range(4):
    print('Train Accuracy of Fold #', i + 1, ' = ', y_train_acc_list[i]*100.0, '%')
print('Train Accuracy Avrage', ' = ', sum(y_train_acc_list)*100.0/ len(y_train_acc_list), '%' )

for i in range(4):
    print('Test Accuracy of Fold #', i + 1, ' = ', y_test_acc_list[i]*100.0, '%')
print('Test Accuracy Avrage', ' = ', sum(y_test_acc_list)*100.0/ len(y_test_acc_list), '%' )

Train Accuracy of Fold # 1  =  97.14285714285714 %
Train Accuracy of Fold # 2  =  97.14285714285714 %
Train Accuracy of Fold # 3  =  97.14285714285714 %
Train Accuracy of Fold # 4  =  97.14285714285714 %
Train Accuracy Avrage  =  97.14285714285714 %
Test Accuracy of Fold # 1  =  73.33333333333333 %
Test Accuracy of Fold # 2  =  95.55555555555556 %
Test Accuracy of Fold # 3  =  95.55555555555556 %
Test Accuracy of Fold # 4  =  97.77777777777777 %
Test Accuracy Avrage  =  90.55555555555556 %


**Result: Confusion Matrix**

In [85]:
for i in range(4):
    print('Train Confusion Matrix #', i + 1, ' = ', '\n', conf_mat_train_list[i])
print('Train Confusion Matrix Avrage', ' = ', '\n', sum(conf_mat_train_list)/ len(y_train_acc_list))

for i in range(4):
    print('Test Confusion Matrix #', i + 1, ' = ', '\n', conf_mat_test_list[i])
print('Test Confusion Matrix Avrage', ' = ', '\n', sum(conf_mat_test_list)/ len(y_test_acc_list))

Train Confusion Matrix # 1  =  
 [[31  0  0]
 [ 0 33  3]
 [ 0  0 38]]
Train Confusion Matrix # 2  =  
 [[35  0  0]
 [ 0 31  3]
 [ 0  0 36]]
Train Confusion Matrix # 3  =  
 [[38  0  0]
 [ 0 28  3]
 [ 0  0 36]]
Train Confusion Matrix # 4  =  
 [[39  0  0]
 [ 0 29  3]
 [ 0  0 34]]
Train Confusion Matrix Avrage  =  
 [[35.75  0.    0.  ]
 [ 0.   30.25  3.  ]
 [ 0.    0.   36.  ]]
Test Confusion Matrix # 1  =  
 [[19  0  0]
 [ 0 13  1]
 [ 0  1 11]]
Test Confusion Matrix # 2  =  
 [[15  0  0]
 [ 0 14  2]
 [ 0  0 14]]
Test Confusion Matrix # 3  =  
 [[12  0  0]
 [ 0 18  1]
 [ 0  0 14]]
Test Confusion Matrix # 4  =  
 [[11  0  0]
 [ 0 17  1]
 [ 0  1 15]]
Test Confusion Matrix Avrage  =  
 [[14.25  0.    0.  ]
 [ 0.   15.5   1.25]
 [ 0.    0.5  13.5 ]]


# **B**

**Bayes Classifier**

In [89]:
class Bayes_Classifier:
    mu = None
    cov = None
    n_classes = None
    def __init__(self):
        a = None
    def pred(self,x):
        prob_vect = np.zeros(self.n_classes)
        for i in range(self.n_classes):
            mnormal = multivariate_normal(mean=bayes_classifier.mu[i], cov=bayes_classifier.cov[i])
            prior = 1./self.n_classes
            prob_vect[i] = prior*mnormal.pdf(x)
            sumatory = 0.
            for j in range(self.n_classes):
                mnormal = multivariate_normal(mean=bayes_classifier.mu[j], cov=bayes_classifier.cov[j])
                sumatory += prior*mnormal.pdf(x)
            prob_vect[i] = prob_vect[i]/sumatory
        return prob_vect
    def fit(self, X,y):
        self.mu = []
        self.cov = []
        self.n_classes = np.max(y)+1
        for i in range(self.n_classes):
            Xc = X[y==i]
            mu_c = np.mean(Xc, axis=0)
            self.mu.append(mu_c)
            cov_c = np.zeros((X.shape[1], X.shape[1]))
            for j in range( Xc.shape[0]):
                a = Xc[j].reshape((X.shape[1],1))
                b = Xc[j].reshape((1,X.shape[1]))
                cov_ci = np.multiply(a, b)
                cov_c = cov_c+cov_ci
            cov_c = cov_c/float(X.shape[0])
            self.cov.append(cov_c)
        self.mu = np.asarray(self.mu)
        self.cov = np.asarray(self.cov)

**Fit & Predict**

In [90]:
# K-Fold
K_fold_cross_val = KFold(n_splits=4, shuffle=True)
K_fold_cross_val.get_n_splits(x_data)

# Lists
y_train_acc_list = []
conf_mat_train_list = []
y_test_acc_list = []
conf_mat_test_list = []

# Fit
for train_index, test_index in K_fold_cross_val.split(x_data):
  x_train, x_test = x_data[train_index], x_data[test_index]
  y_train, y_test = y_data[train_index], y_data[test_index]
  bayes_classifier = Bayes_Classifier()
  bayes_classifier.fit(x_train,y_train)
  # Pridict
  y_train_pred = []
  for i in range(x_train.shape[0]):
    y_train_pred_prob = bayes_classifier.pred(x_train[i,:])
    if (y_train_pred_prob[0] > y_train_pred_prob[1]) & (y_train_pred_prob[0] > y_train_pred_prob[2]):
      y_train_pred.append(0)
    elif (y_train_pred_prob[1] > y_train_pred_prob[0]) & (y_train_pred_prob[1] > y_train_pred_prob[2]):
      y_train_pred.append(1)
    else :
      y_train_pred.append(2)
  y_train_pred = np.array(y_train_pred)
  y_test_pred = []
  for i in range(x_test.shape[0]):
    y_test_pred_prob = bayes_classifier.pred(x_test[i,:])
    if (y_test_pred_prob[0] > y_test_pred_prob[1]) & (y_test_pred_prob[0] > y_test_pred_prob[2]):
      y_test_pred.append(0)
    elif (y_test_pred_prob[1] > y_test_pred_prob[0]) & (y_test_pred_prob[1] > y_test_pred_prob[2]):
      y_test_pred.append(1)
    else :
      y_test_pred.append(2)
  y_test_acc_list.append(y_test_acc)

  # Train: Accuracy & Confusion Matrix
  y_train_acc = accuracy_score(y_train, y_train_pred)
  y_train_acc_list.append(y_train_acc)
  conf_mat_train = confusion_matrix(y_train, y_train_pred)
  conf_mat_train_list.append(conf_mat_train)

  # Test: Accuracy & Confusion Matrix
  y_test_pred = np.array(y_test_pred)
  y_test_acc = accuracy_score(y_test, y_test_pred)
  conf_mat_test = confusion_matrix(y_test, y_test_pred)
  conf_mat_test_list.append(conf_mat_test)


**Result: Accuracy**

In [91]:
for i in range(4):
    print('Train Accuracy of Fold #', i + 1, ' = ', y_train_acc_list[i]*100.0, '%')
print('Train Accuracy Avrage', ' = ', sum(y_train_acc_list)*100.0/ len(y_train_acc_list), '%' )

for i in range(4):
    print('Test Accuracy of Fold #', i + 1, ' = ', y_test_acc_list[i]*100.0, '%')
print('Test Accuracy Avrage', ' = ', sum(y_test_acc_list)*100.0/ len(y_test_acc_list), '%' )

Train Accuracy of Fold # 1  =  98.21428571428571 %
Train Accuracy of Fold # 2  =  96.42857142857143 %
Train Accuracy of Fold # 3  =  94.69026548672566 %
Train Accuracy of Fold # 4  =  96.46017699115043 %
Train Accuracy Avrage  =  96.44832490518331 %
Test Accuracy of Fold # 1  =  95.55555555555556 %
Test Accuracy of Fold # 2  =  94.73684210526315 %
Test Accuracy of Fold # 3  =  97.36842105263158 %
Test Accuracy of Fold # 4  =  100.0 %
Test Accuracy Avrage  =  96.91520467836257 %


**Result: Confusion Matrix**

In [92]:
for i in range(4):
    print('Train Confusion Matrix of Fold #', i + 1, ' = ', '\n', conf_mat_train_list[i])
print('Train Confusion Matrix Avrage', ' = ', '\n', sum(conf_mat_train_list)/ len(y_train_acc_list))

for i in range(4):
    print('Test Confusion Matrix of Fold #', i + 1, ' = ', '\n', conf_mat_test_list[i])
print('Test Confusion Matrix Avrage', ' = ', '\n', sum(conf_mat_test_list)/ len(y_test_acc_list))

Train Confusion Matrix of Fold # 1  =  
 [[41  0  0]
 [ 0 33  2]
 [ 0  0 36]]
Train Confusion Matrix of Fold # 2  =  
 [[34  0  0]
 [ 0 38  3]
 [ 0  1 36]]
Train Confusion Matrix of Fold # 3  =  
 [[38  0  0]
 [ 0 33  5]
 [ 0  1 36]]
Train Confusion Matrix of Fold # 4  =  
 [[37  0  0]
 [ 0 33  3]
 [ 0  1 39]]
Train Confusion Matrix Avrage  =  
 [[37.5   0.    0.  ]
 [ 0.   34.25  3.25]
 [ 0.    0.75 36.75]]
Test Confusion Matrix of Fold # 1  =  
 [[ 9  0  0]
 [ 0 13  2]
 [ 0  0 14]]
Test Confusion Matrix of Fold # 2  =  
 [[16  0  0]
 [ 0  9  0]
 [ 0  1 12]]
Test Confusion Matrix of Fold # 3  =  
 [[12  0  0]
 [ 0 12  0]
 [ 0  0 13]]
Test Confusion Matrix of Fold # 4  =  
 [[13  0  0]
 [ 0 12  2]
 [ 0  0 10]]
Test Confusion Matrix Avrage  =  
 [[12.5   0.    0.  ]
 [ 0.   11.5   1.  ]
 [ 0.    0.25 12.25]]


# **C**

**A**

In [70]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.25)

class Bayes_Classifier:
    mu = None
    cov = None
    n_classes = None
    def __init__(self):
        a = None
    def pred(self,x):
        prob_vect = np.zeros(self.n_classes)
        for i in range(self.n_classes):
            mnormal = multivariate_normal(mean=bayes_classifier.mu[i], cov=bayes_classifier.cov[i])
            for k in range(bayes_classifier.cov.shape[-1]):
              for j in range(bayes_classifier.cov.shape[-1]):
                if k!=j:
                  bayes_classifier.cov[:, k, j] = 0.0
            prior = 1./self.n_classes
            prob_vect[i] = prior*mnormal.pdf(x)
            sumatory = 0.
            for j in range(self.n_classes):
                mnormal = multivariate_normal(mean=bayes_classifier.mu[j], cov=bayes_classifier.cov[j])
                sumatory += prior*mnormal.pdf(x)
            prob_vect[i] = prob_vect[i]/sumatory
        return prob_vect
    def fit(self, X,y):
        self.mu = []
        self.cov = []
        self.n_classes = np.max(y)+1
        for i in range(self.n_classes):
            Xc = X[y==i]
            mu_c = np.mean(Xc, axis=0)
            self.mu.append(mu_c)
            cov_c = np.zeros((X.shape[1], X.shape[1]))
            for j in range( Xc.shape[0]):
                a = Xc[j].reshape((X.shape[1],1))
                b = Xc[j].reshape((1,X.shape[1]))
                cov_ci = np.multiply(a, b)
                cov_c = cov_c+cov_ci
            cov_c = cov_c/float(X.shape[0])
            self.cov.append(cov_c)
        self.mu = np.asarray(self.mu)
        self.cov = np.asarray(self.cov)

# Fit
bayes_classifier = Bayes_Classifier()
bayes_classifier.fit(x_train,y_train)

# Pridict
# Train Data
y_train_pred = []
for i in range(x_train.shape[0]):
  y_train_pred_prob = bayes_classifier.pred(x_train[i,:])
  if (y_train_pred_prob[0] > y_train_pred_prob[1]) & (y_train_pred_prob[0] > y_train_pred_prob[2]):
    y_train_pred.append(0)
  elif (y_train_pred_prob[1] > y_train_pred_prob[0]) & (y_train_pred_prob[1] > y_train_pred_prob[2]):
    y_train_pred.append(1)
  else :
    y_train_pred.append(2)
y_train_pred = np.array(y_train_pred)

# Test Data
y_test_pred = []
for i in range(x_test.shape[0]):
  y_test_pred_prob = bayes_classifier.pred(x_test[i,:])
  if (y_test_pred_prob[0] > y_test_pred_prob[1]) & (y_test_pred_prob[0] > y_test_pred_prob[2]):
    y_test_pred.append(0)
  elif (y_test_pred_prob[1] > y_test_pred_prob[0]) & (y_test_pred_prob[1] > y_test_pred_prob[2]):
    y_test_pred.append(1)
  else :
    y_test_pred.append(2)
y_test_pred = np.array(y_test_pred)

y_train_acc = accuracy_score(y_train, y_train_pred)
print('Train Accuracy',' = ', y_train_acc*100.0, '%')
y_test_acc = accuracy_score(y_test, y_test_pred)
print('Test Accuracy',' = ', y_test_acc*100.0, '%')

conf_mat_train = confusion_matrix(y_train, y_train_pred)
print('Train Confusion Matrix', ' = ', '\n', conf_mat_train)
conf_mat_test = confusion_matrix(y_test, y_test_pred)
print('Test Confusion Matrix', ' = ', '\n', conf_mat_test)

Train Accuracy  =  82.14285714285714 %
Test Accuracy  =  71.05263157894737 %
Train Confusion Matrix  =  
 [[35  0  0]
 [ 0 40  0]
 [ 0 20 17]]
Test Confusion Matrix  =  
 [[15  0  0]
 [ 0 10  0]
 [ 0 11  2]]


**B**

In [71]:
class Bayes_Classifier:
    mu = None
    cov = None
    n_classes = None
    def __init__(self):
        a = None
    def pred(self,x):
        prob_vect = np.zeros(self.n_classes)
        for i in range(self.n_classes):
            mnormal = multivariate_normal(mean=bayes_classifier.mu[i], cov=bayes_classifier.cov[i])
            for k in range(bayes_classifier.cov.shape[-1]):
              for j in range(bayes_classifier.cov.shape[-1]):
                if k!=j:
                  bayes_classifier.cov[:, k, j] = 0.0
            prior = 1./self.n_classes
            prob_vect[i] = prior*mnormal.pdf(x)
            sumatory = 0.
            for j in range(self.n_classes):
                mnormal = multivariate_normal(mean=bayes_classifier.mu[j], cov=bayes_classifier.cov[j])
                sumatory += prior*mnormal.pdf(x)
            prob_vect[i] = prob_vect[i]/sumatory
        return prob_vect
    def fit(self, X,y):
        self.mu = []
        self.cov = []
        self.n_classes = np.max(y)+1
        for i in range(self.n_classes):
            Xc = X[y==i]
            mu_c = np.mean(Xc, axis=0)
            self.mu.append(mu_c)
            cov_c = np.zeros((X.shape[1], X.shape[1]))
            for j in range( Xc.shape[0]):
                a = Xc[j].reshape((X.shape[1],1))
                b = Xc[j].reshape((1,X.shape[1]))
                cov_ci = np.multiply(a, b)
                cov_c = cov_c+cov_ci
            cov_c = cov_c/float(X.shape[0])
            self.cov.append(cov_c)
        self.mu = np.asarray(self.mu)
        self.cov = np.asarray(self.cov)

# K-Fold
K_fold_cross_val = KFold(n_splits=4, shuffle=True)
K_fold_cross_val.get_n_splits(x_data)

# Lists
y_train_acc_list = []
conf_mat_train_list = []
y_test_acc_list = []
conf_mat_test_list = []

# Fit
for train_index, test_index in K_fold_cross_val.split(x_data):
  x_train, x_test = x_data[train_index], x_data[test_index]
  y_train, y_test = y_data[train_index], y_data[test_index]
  bayes_classifier = Bayes_Classifier()
  bayes_classifier.fit(x_train,y_train)
  # Pridict
  y_train_pred = []
  for i in range(x_train.shape[0]):
    y_train_pred_prob = bayes_classifier.pred(x_train[i,:])
    if (y_train_pred_prob[0] > y_train_pred_prob[1]) & (y_train_pred_prob[0] > y_train_pred_prob[2]):
      y_train_pred.append(0)
    elif (y_train_pred_prob[1] > y_train_pred_prob[0]) & (y_train_pred_prob[1] > y_train_pred_prob[2]):
      y_train_pred.append(1)
    else :
      y_train_pred.append(2)
  y_train_pred = np.array(y_train_pred)
  y_test_pred = []
  for i in range(x_test.shape[0]):
    y_test_pred_prob = bayes_classifier.pred(x_test[i,:])
    if (y_test_pred_prob[0] > y_test_pred_prob[1]) & (y_test_pred_prob[0] > y_test_pred_prob[2]):
      y_test_pred.append(0)
    elif (y_test_pred_prob[1] > y_test_pred_prob[0]) & (y_test_pred_prob[1] > y_test_pred_prob[2]):
      y_test_pred.append(1)
    else :
      y_test_pred.append(2)
  y_test_acc_list.append(y_test_acc)

  # Train: Accuracy & Confusion Matrix
  y_train_acc = accuracy_score(y_train, y_train_pred)
  y_train_acc_list.append(y_train_acc)
  conf_mat_train = confusion_matrix(y_train, y_train_pred)
  conf_mat_train_list.append(conf_mat_train)

  # Test: Accuracy & Confusion Matrix
  y_test_pred = np.array(y_test_pred)
  y_test_acc = accuracy_score(y_test, y_test_pred)
  conf_mat_test = confusion_matrix(y_test, y_test_pred)
  conf_mat_test_list.append(conf_mat_test)


for i in range(4):
    print('Train Accuracy of Fold #', i + 1, ' = ', y_train_acc_list[i]*100.0, '%')
print('Train Accuracy Avrage', ' = ', sum(y_train_acc_list)*100.0/ len(y_train_acc_list), '%' )

for i in range(4):
    print('Test Accuracy of Fold #', i + 1, ' = ', y_test_acc_list[i]*100.0, '%')
print('Test Accuracy Avrage', ' = ', sum(y_test_acc_list)*100.0/ len(y_test_acc_list), '%' )

for i in range(4):
    print('Train Confusion Matrix of Fold #', i + 1, ' = ', '\n', conf_mat_train_list[i])
print('Train Confusion Matrix Avrage', ' = ', '\n', sum(conf_mat_train_list)/ len(y_train_acc_list))

for i in range(4):
    print('Test Confusion Matrix of Fold #', i + 1, ' = ', '\n', conf_mat_test_list[i])
print('Test Confusion Matrix Avrage', ' = ', '\n', sum(conf_mat_test_list)/ len(y_test_acc_list))

Train Accuracy of Fold # 1  =  73.21428571428571 %
Train Accuracy of Fold # 2  =  70.53571428571429 %
Train Accuracy of Fold # 3  =  76.10619469026548 %
Train Accuracy of Fold # 4  =  84.070796460177 %
Train Accuracy Avrage  =  75.98174778761062 %
Test Accuracy of Fold # 1  =  71.05263157894737 %
Test Accuracy of Fold # 2  =  76.31578947368422 %
Test Accuracy of Fold # 3  =  78.94736842105263 %
Test Accuracy of Fold # 4  =  75.67567567567568 %
Test Accuracy Avrage  =  75.49786628733999 %
Train Confusion Matrix of Fold # 1  =  
 [[34  0  0]
 [ 0 38  0]
 [ 0 30 10]]
Train Confusion Matrix of Fold # 2  =  
 [[37  0  0]
 [ 0 36  0]
 [ 0 33  6]]
Train Confusion Matrix of Fold # 3  =  
 [[40  0  0]
 [ 0 36  0]
 [ 0 27 10]]
Train Confusion Matrix of Fold # 4  =  
 [[39  0  0]
 [ 0 40  0]
 [ 0 18 16]]
Train Confusion Matrix Avrage  =  
 [[37.5  0.   0. ]
 [ 0.  37.5  0. ]
 [ 0.  27.  10.5]]
Test Confusion Matrix of Fold # 1  =  
 [[16  0  0]
 [ 0 12  0]
 [ 0  9  1]]
Test Confusion Matrix of Fo

# **D**

**Naive Bayes Classifier**

In [72]:
def separate_by_class(dataset):
	separated = dict()
	for i in range(len(dataset)):
		vector = dataset[i]
		class_value = vector[-1]
		if (class_value not in separated):
			separated[class_value] = list()
		separated[class_value].append(vector)
	return separated

def mean(numbers):
	return sum(numbers)/float(len(numbers))

def stdev(numbers):
	avg = mean(numbers)
	variance = sum([(x-avg)**2 for x in numbers]) / float(len(numbers)-1)
	return sqrt(variance)

def summarize_dataset(dataset):
	summaries = [(mean(column), stdev(column), len(column)) for column in zip(*dataset)]
	del(summaries[-1])
	return summaries

def summarize_by_class(dataset):
	separated = separate_by_class(dataset)
	summaries = dict()
	for class_value, rows in separated.items():
		summaries[class_value] = summarize_dataset(rows)
	return summaries

def calculate_probability(x, mean, stdev):
	exponent = exp(-((x-mean)**2 / (2 * stdev**2 )))
	return (1 / (sqrt(2 * pi) * stdev)) * exponent

def calculate_class_probabilities(summaries, row):
	total_rows = sum([summaries[label][0][2] for label in summaries])
	probabilities = dict()
	for class_value, class_summaries in summaries.items():
		probabilities[class_value] = summaries[class_value][0][2]/float(total_rows)
		for i in range(len(class_summaries)):
			mean, stdev, _ = class_summaries[i]
			probabilities[class_value] *= calculate_probability(row[i], mean, stdev)
	return probabilities

def calculate_output(data_input):
   output=[]
   for i in range(len(data_input)):
     summaries = summarize_by_class(data_train)
     probabilities = calculate_class_probabilities(summaries, data_input[i])
     output.append(max(probabilities, key=probabilities.get))
   return  np.array(output)  

def naive_bayes(train, test):
	summarize = summarize_by_class(train)
	predictions = list()
	for row in test:
		output = predict(summarize, row)
		predictions.append(output)
	return(predictions)

def predict(summaries, row):
	probabilities = calculate_class_probabilities(summaries, row)
	best_label, best_prob = None, -1
	for class_value, probability in probabilities.items():
		if best_label is None or probability > best_prob:
			best_prob = probability
			best_label = class_value
	return best_label

**Fit & Predict**

In [73]:
# Lists
y_train_acc_list = []
conf_mat_train_list = []
y_test_acc_list = []
conf_mat_test_list = []

for i in range(4):
  # Splite
  x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.30)
  # Train
  y_train_pred = naive_bayes(np.concatenate([x_train, y_train.reshape(-1,1)],axis=1), np.concatenate([x_train, y_train.reshape(-1,1)],axis=1))
  y_train_acc = accuracy_score(y_train, y_train_pred)
  y_train_acc_list.append(y_train_acc)
  conf_mat_train = confusion_matrix(y_train, y_train_pred)
  conf_mat_train_list.append(conf_mat_train)
  # Test
  y_test_pred = naive_bayes(np.concatenate([x_train, y_train.reshape(-1,1)],axis=1), np.concatenate([x_test, y_test.reshape(-1,1)],axis=1))
  y_test_acc = accuracy_score(y_test, y_test_pred)
  y_test_acc_list.append(y_test_acc)
  conf_mat_test = confusion_matrix(y_test, y_test_pred)
  conf_mat_test_list.append(conf_mat_test)

# Result
print('Train Accuracy Avrage', ' = ', sum(y_train_acc_list)*100.0/ len(y_train_acc_list), '%' )
print('Test Accuracy Avrage', ' = ', sum(y_test_acc_list)*100.0/ len(y_test_acc_list), '%' )
print('Train Confusion Matrix Avrage', ' = ', '\n', sum(conf_mat_train_list)/ len(y_train_acc_list))
print('Test Confusion Matrix Avrage', ' = ', '\n', sum(conf_mat_test_list)/ len(y_test_acc_list))


Train Accuracy Avrage  =  95.95238095238095 %
Test Accuracy Avrage  =  95.55555555555554 %
Train Confusion Matrix Avrage  =  
 [[34.25  0.    0.  ]
 [ 0.   33.5   2.  ]
 [ 0.    2.25 33.  ]]
Test Confusion Matrix Avrage  =  
 [[15.75  0.    0.  ]
 [ 0.   14.    0.5 ]
 [ 0.    1.5  13.25]]


# **E**

**Naive Bayes Classifier**

In [74]:
def separate_by_class(dataset):
	separated = dict()
	for i in range(len(dataset)):
		vector = dataset[i]
		class_value = vector[-1]
		if (class_value not in separated):
			separated[class_value] = list()
		separated[class_value].append(vector)
	return separated

def mean(numbers):
	return sum(numbers)/float(len(numbers))
 
def stdev(numbers):
	avg = mean(numbers)
	variance = sum([(x-avg)**2 for x in numbers]) / float(len(numbers)-1)
	return sqrt(variance)
 
def summarize_dataset(dataset):
	summaries = [(mean(column), stdev(column), len(column)) for column in zip(*dataset)]
	del(summaries[-1])
	return summaries
 
def summarize_by_class(dataset):
	separated = separate_by_class(dataset)
	summaries = dict()
	for class_value, rows in separated.items():
		summaries[class_value] = summarize_dataset(rows)
	return summaries
 
def calculate_probability(x, mean, stdev):
	exponent = exp(-((x-mean)**2 / (2 * stdev**2 )))
	return (1 / (sqrt(2 * pi) * stdev)) * exponent
 
def calculate_class_probabilities(summaries, row):
	total_rows = sum([summaries[label][0][2] for label in summaries])
	probabilities = dict()
	for class_value, class_summaries in summaries.items():
		probabilities[class_value] = summaries[class_value][0][2]/float(total_rows)
		for i in range(len(class_summaries)):
			mean, stdev, _ = class_summaries[i]
			probabilities[class_value] *= calculate_probability(row[i], mean, stdev)
	return probabilities

def calculate_output(data_input):
   output=[]
   for i in range(len(data_input)):
     summaries = summarize_by_class(data_train)
     probabilities = calculate_class_probabilities(summaries, data_input[i])
     output.append(max(probabilities, key=probabilities.get))
   return  np.array(output)  

def naive_bayes(train, test):
	summarize = summarize_by_class(train)
	predictions = list()
	for row in test:
		output = predict(summarize, row)
		predictions.append(output)
	return(predictions)
 
def predict(summaries, row):
	probabilities = calculate_class_probabilities(summaries, row)
	best_label, best_prob = None, -1
	for class_value, probability in probabilities.items():
		if best_label is None or probability > best_prob:
			best_prob = probability
			best_label = class_value
	return best_label

**Fit & Predict**

In [75]:
# K-Fold
K_fold_cross_val = KFold(n_splits=4, shuffle=True)
K_fold_cross_val.get_n_splits(x_data)

# Lists
y_train_acc_list = []
conf_mat_train_list = []
y_test_acc_list = []
conf_mat_test_list = []

# Fit
for train_index, test_index in K_fold_cross_val.split(x_data):
  x_train, x_test = x_data[train_index], x_data[test_index]
  y_train, y_test = y_data[train_index], y_data[test_index]
  # Train
  y_train_pred = naive_bayes(np.concatenate([x_train, y_train.reshape(-1,1)],axis=1), np.concatenate([x_train, y_train.reshape(-1,1)],axis=1))
  y_train_acc = accuracy_score(y_train, y_train_pred)
  y_train_acc_list.append(y_train_acc)
  conf_mat_train = confusion_matrix(y_train, y_train_pred)
  conf_mat_train_list.append(conf_mat_train)
  # Test
  y_test_pred = naive_bayes(np.concatenate([x_train, y_train.reshape(-1,1)],axis=1), np.concatenate([x_test, y_test.reshape(-1,1)],axis=1))
  y_test_acc = accuracy_score(y_test, y_test_pred)
  y_test_acc_list.append(y_test_acc)
  conf_mat_test = confusion_matrix(y_test, y_test_pred)
  conf_mat_test_list.append(conf_mat_test)

# Result
print('Train Accuracy Avrage', ' = ', sum(y_train_acc_list)*100.0/ len(y_train_acc_list), '%' )
print('Test Accuracy Avrage', ' = ', sum(y_test_acc_list)*100.0/ len(y_test_acc_list), '%' )
print('Train Confusion Matrix Avrage', ' = ', '\n', sum(conf_mat_train_list)/ len(y_train_acc_list))
print('Test Confusion Matrix Avrage', ' = ', '\n', sum(conf_mat_test_list)/ len(y_test_acc_list))

Train Accuracy Avrage  =  95.77670670037925 %
Test Accuracy Avrage  =  95.98150782361307 %
Train Confusion Matrix Avrage  =  
 [[37.5   0.    0.  ]
 [ 0.   35.5   2.  ]
 [ 0.    2.75 34.75]]
Test Confusion Matrix Avrage  =  
 [[12.5   0.    0.  ]
 [ 0.   11.75  0.75]
 [ 0.    0.75 11.75]]
